### Boston 집값 예제 
#### - Linear regression 

In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import MinMaxScaler, PolynomialFeatures
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split

In [2]:
boston = load_boston() 

In [3]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [4]:
boston.data.shape

(506, 13)

In [5]:
boston.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [6]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [7]:
boston.DESCR

"Boston House Prices dataset\n===========================\n\nNotes\n------\nData Set Characteristics:  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive\n    \n    :Median Value (attribute 14) is usually the target\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per $10,000\n

In [8]:
X = boston.data
y = boston.target

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [9]:
lr = LinearRegression().fit(X_train, y_train)

In [10]:
lr.score(X_train, y_train)

0.769744837056394

In [11]:
lr.score(X_test, y_test)

0.6353620786674616

In [12]:
lr.coef_

array([-1.16869578e-01,  4.39939421e-02, -5.34808462e-03,  2.39455391e+00,
       -1.56298371e+01,  3.76145473e+00, -6.95007160e-03, -1.43520477e+00,
        2.39755946e-01, -1.12937318e-02, -9.86626289e-01,  8.55687565e-03,
       -5.00029440e-01])

### polynomial 적용

In [13]:
def load_extended_boston():
    boston = load_boston() 
    X = MinMaxScaler().fit_transform(boston.data)
    P = PolynomialFeatures(degree=2, include_bias=False)    
    X = P.fit_transform(X)
    print(P.get_feature_names())
    return X, boston.target

In [14]:
X, y = load_extended_boston()

['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11', 'x12', 'x0^2', 'x0 x1', 'x0 x2', 'x0 x3', 'x0 x4', 'x0 x5', 'x0 x6', 'x0 x7', 'x0 x8', 'x0 x9', 'x0 x10', 'x0 x11', 'x0 x12', 'x1^2', 'x1 x2', 'x1 x3', 'x1 x4', 'x1 x5', 'x1 x6', 'x1 x7', 'x1 x8', 'x1 x9', 'x1 x10', 'x1 x11', 'x1 x12', 'x2^2', 'x2 x3', 'x2 x4', 'x2 x5', 'x2 x6', 'x2 x7', 'x2 x8', 'x2 x9', 'x2 x10', 'x2 x11', 'x2 x12', 'x3^2', 'x3 x4', 'x3 x5', 'x3 x6', 'x3 x7', 'x3 x8', 'x3 x9', 'x3 x10', 'x3 x11', 'x3 x12', 'x4^2', 'x4 x5', 'x4 x6', 'x4 x7', 'x4 x8', 'x4 x9', 'x4 x10', 'x4 x11', 'x4 x12', 'x5^2', 'x5 x6', 'x5 x7', 'x5 x8', 'x5 x9', 'x5 x10', 'x5 x11', 'x5 x12', 'x6^2', 'x6 x7', 'x6 x8', 'x6 x9', 'x6 x10', 'x6 x11', 'x6 x12', 'x7^2', 'x7 x8', 'x7 x9', 'x7 x10', 'x7 x11', 'x7 x12', 'x8^2', 'x8 x9', 'x8 x10', 'x8 x11', 'x8 x12', 'x9^2', 'x9 x10', 'x9 x11', 'x9 x12', 'x10^2', 'x10 x11', 'x10 x12', 'x11^2', 'x11 x12', 'x12^2']


In [15]:
X.shape

(506, 104)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
lr = LinearRegression().fit(X_train, y_train)

In [17]:
lr.score(X_train, y_train)

0.9523526436864238

In [18]:
lr.score(X_test, y_test)

0.6057754892935958

### Ridge 적용

In [19]:
def load_extended_boston():
    boston = load_boston() 
    X = MinMaxScaler().fit_transform(boston.data)
    X = PolynomialFeatures(degree=2, include_bias=False).fit_transform(X)
    return X, boston.target
X, y = load_extended_boston()

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [20]:
from sklearn.linear_model import Ridge
ridge = Ridge().fit(X_train, y_train)
ridge.score(X_train, y_train) , ridge.score(X_test, y_test)

(0.8860578560395833, 0.7527139600306938)

In [21]:
ridge10 = Ridge(alpha=10).fit(X_train, y_train)
ridge10.score(X_train, y_train) , ridge10.score(X_test, y_test)

(0.7883461511233252, 0.6358967327447733)

In [22]:
ridge01 = Ridge(alpha=0.1).fit(X_train, y_train)
ridge01.score(X_train, y_train) , ridge01.score(X_test, y_test)

(0.928578208201073, 0.7717933688844779)

### 시각화

In [23]:
import matplotlib.pyplot as plt 

plt.plot(ridge10.coef_, '^', label="Ridge alpha=10")
plt.plot(ridge.coef_, 's', label="Ridge alpha=1")
plt.plot(ridge01.coef_, 'v', label="Ridge alpha=0.1")
plt.plot(lr.coef_, 'o', label="Linear Regreesion")
xlims = plt.xlim()
plt.hlines(0, xlims[0],xlims[1])
plt.xlim(xlims)
plt.ylim(-25,25)
plt.legend()
plt.show()

<Figure size 640x480 with 1 Axes>

### Lasso 적용

In [24]:
def load_extended_boston():
    boston = load_boston() 
    X = MinMaxScaler().fit_transform(boston.data)
    X = PolynomialFeatures(degree=2, include_bias=True).fit_transform(X)
    print(X.shape)
    return X, boston.target
X, y = load_extended_boston()

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

(506, 105)


In [25]:
from sklearn.linear_model import Lasso
lasso = Lasso().fit(X_train, y_train)
lasso.score(X_train, y_train), lasso.score(X_test, y_test)

(0.29323768991114607, 0.20937503255272316)

In [26]:
import numpy as np
np.sum(lasso.coef_ != 0)

4

In [27]:
lasso001 = Lasso(alpha=0.01, max_iter=100000).fit(X_train, y_train)
lasso001.score(X_train, y_train), lasso001.score(X_test, y_test)

(0.8965069559751289, 0.7656489887843522)

In [28]:
np.sum(lasso001.coef_ != 0)

33

In [29]:
lasso0001 = Lasso(alpha=0.0001, max_iter=100000).fit(X_train, y_train)
lasso0001.score(X_train, y_train), lasso0001.score(X_test, y_test)

(0.9510610436181262, 0.6403098994160419)

In [30]:
np.sum(lasso0001.coef_ != 0)

94

In [31]:
def load_extended_boston():
    boston = load_boston() 
    X = MinMaxScaler().fit_transform(boston.data)
    X = PolynomialFeatures(degree=2, include_bias=True).fit_transform(X)
    print(X.shape)
    return X, boston.target
X, y = load_extended_boston()

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

(506, 105)


In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
lr = LinearRegression().fit(X_train, y_train)

In [33]:
lr.coef_.shape, lr.intercept_

((105,), 31.645174101369133)

In [34]:
lr.coef_

array([-5.49919638e-10, -4.02752236e+02, -5.00710011e+01, -1.33316908e+02,
       -1.20021023e+01, -1.27106873e+01,  2.83052585e+01,  5.44920273e+01,
       -5.17339345e+01,  2.52602789e+01,  3.64990704e+01, -1.01038605e+01,
       -1.96288897e+01, -2.13677312e+01,  1.46473758e+01,  2.89505391e+03,
        1.51026852e+03,  1.17995400e+02, -2.65658068e+01,  3.12488451e+01,
       -3.14463610e+01,  4.52535825e+01,  1.28349557e+03, -2.24600306e+03,
        2.22198614e+02, -4.66264354e-01,  4.07661992e+01, -1.34357879e+01,
       -1.90960479e+01, -2.77605103e+00, -8.09710327e+01,  9.73141885e+00,
        5.13324280e+00, -7.87928926e-01, -7.60269229e+00,  3.36717627e+01,
       -1.15051345e+01,  6.62672250e+01, -1.75632324e+01,  4.29826712e+01,
        1.27662043e+00,  6.09633677e-01,  5.71868313e+01,  1.40823103e+01,
        5.53404218e+01, -3.03481907e+01,  1.88121756e+01, -1.37772336e+01,
        6.09790464e+01, -1.25792000e+01, -1.20021023e+01, -1.76980605e+01,
       -3.40279371e+01,  

### Polynomial Feature 상세 보기 

In [35]:
boston = load_boston() 
X = MinMaxScaler().fit_transform(boston.data)
P = PolynomialFeatures(degree=2, include_bias=False)    
X = P.fit_transform(X)
print(P.get_feature_names())

['x0', 'x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9', 'x10', 'x11', 'x12', 'x0^2', 'x0 x1', 'x0 x2', 'x0 x3', 'x0 x4', 'x0 x5', 'x0 x6', 'x0 x7', 'x0 x8', 'x0 x9', 'x0 x10', 'x0 x11', 'x0 x12', 'x1^2', 'x1 x2', 'x1 x3', 'x1 x4', 'x1 x5', 'x1 x6', 'x1 x7', 'x1 x8', 'x1 x9', 'x1 x10', 'x1 x11', 'x1 x12', 'x2^2', 'x2 x3', 'x2 x4', 'x2 x5', 'x2 x6', 'x2 x7', 'x2 x8', 'x2 x9', 'x2 x10', 'x2 x11', 'x2 x12', 'x3^2', 'x3 x4', 'x3 x5', 'x3 x6', 'x3 x7', 'x3 x8', 'x3 x9', 'x3 x10', 'x3 x11', 'x3 x12', 'x4^2', 'x4 x5', 'x4 x6', 'x4 x7', 'x4 x8', 'x4 x9', 'x4 x10', 'x4 x11', 'x4 x12', 'x5^2', 'x5 x6', 'x5 x7', 'x5 x8', 'x5 x9', 'x5 x10', 'x5 x11', 'x5 x12', 'x6^2', 'x6 x7', 'x6 x8', 'x6 x9', 'x6 x10', 'x6 x11', 'x6 x12', 'x7^2', 'x7 x8', 'x7 x9', 'x7 x10', 'x7 x11', 'x7 x12', 'x8^2', 'x8 x9', 'x8 x10', 'x8 x11', 'x8 x12', 'x9^2', 'x9 x10', 'x9 x11', 'x9 x12', 'x10^2', 'x10 x11', 'x10 x12', 'x11^2', 'x11 x12', 'x12^2']


### Elasitic Net 

In [36]:
from sklearn.linear_model import ElasticNet

lm_elastic = ElasticNet(alpha=0.01) 
lm_elastic.fit(X_train, y_train)
lm_elastic.score(X_test, y_test)

0.7208963094031802